### ISSUE TITLE
tranform method fails 

### ISSUE THREAD

**Issue by henrikblunck** [PI-BO/OPA_TAD_PAD#3]
Isn't the transform method not to be found this internal one ?

https://github.com/PAD-Protecting-Anonymity/PAD/blob/e43784cdfcc0ef6795a2c9bb575872fce127023d/metric_learning/deep_metric_learning1.py#L50

**Comment by benjamin-albrecht** [comment]
No the deep_metric_learning.py module is not imported/used in our case.
The issue occurs at the following point: https://github.com/PI-BO/OPA_TAD_PAD/blob/master/utilities/subsampling.py#L98
`dist = dist_metric.transform(pair)`

The type of dist_metric is: numpy.matrixlib.defmatrix.matrix

> Traceback (most recent call last):
  File "demo_efficient_labeling.py", line 262, in <module>
    seed=seed_vec[mc_i])
  File "../utilities/subsampling.py", line 76, in active_sampling
    uncertainty = self.get_uncertainty_entropy_deep(pair=pair[0], dist_metric=dist_metric, mu=0)
  File "../utilities/subsampling.py", line 98, in get_uncertainty_entropy_deep
    dist = dist_metric.transform(pair)
AttributeError: 'matrix' object has no attribute 'transform'

**Comment by henrikblunck** [comment]
Avoided / Solved in commit a504b32ed4242f646093d46238926991985d13fc . 
Hatte es bislang nicht funktioniert mit der alternativen Methode, oder wurde es noch nicht ausprobiert? In jedem Falle lohnt es sich die Berechnung mit Kapitel 5.3 abzugleichen?
